# Generated by Django 4.1.5 on 2023-01-20 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["due_date"]},
        ),
    ]
