version: '3.8'
services:
  frontend:
    image: node:latest
    command: npm start
    working_dir: /app
    volumes:
      - ./frontend:/app
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - NODE_ENV=development
    ports:
      - "3000:3000"
    container_name: Frontend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    container_name: Backend
#   database:
#     image: postgres:14
#     container_name: Database
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#       - ./database/setup:/docker-entrypoint-initdb.d
#     environment:
#       - POSTGRES_MULTIPLE_DATABASES=frontend
#       - POSTGRES_PASSWORD=test-databases
#     ports:
#       - 15432:5432
# volumes:
#   pgdata:
