version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    container_name: Frontend
    ports:
      - 3000:3000
    environment:
      - NODE_ENV= development
    depends_on:
      - database
  database:
    image: postgres:14
    container_name: Database
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/setup:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_MULTIPLE_DATABASES=frontend
      - POSTGRES_PASSWORD=test-databases
    ports:
      - 15432:5432
volumes:
  pgdata:
  node_modules:
